---
services:
  ubnt:
    image: nginx:1.28.0-alpine-slim
    hostname: ubnt
    container_name: ubnt
    restart: always
    volumes:
      - ./conf/resolv.conf:/etc/resolv.conf:ro
      - ./conf/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./conf/nginx/stream.d/stream-ubnt.conf:/etc/nginx/stream.d/stream-ubnt.conf:ro
    ports:
      - "443:443/tcp"
    deploy:
      resources:
        limits:
          cpus: '0.75'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 256M
